"""Tabler."""

__title__ = "labeler"
__description__ = "Easily create PDF documents for printing on label paper"
__url__ = "http://github.com/lukeshiner/labeler.git"
__version__ = "0.0.1"
__author__ = "Luke Shiner"
__author_email__ = "luke@lukeshiner.com"
__license__ = "MIT"
__copyright__ = "Copyright 2018 Luke Shiner"
